ubuntu@ip-172-31-42-97:~/teleaccount-bot$ sudo nano /etc/systemd/system/telebot.service
ubuntu@ip-172-31-42-97:~/teleaccount-bot$ sudo systemctl daemon-reload
ubuntu@ip-172-31-42-97:~/teleaccount-bot$ sudo systemctl restart telebot
ubuntu@ip-172-31-42-97:~/teleaccount-bot$ sudo systemctl status telebot
‚óè telebot.service - Telegram Account Selling Bot
     Loaded: loaded (/etc/systemd/system/telebot.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2025-10-22 13:57:29 UTC; 3s ago
    Process: 28361 ExecStart=/usr/bin/python3 -u /home/ubuntu/teleaccount-bot/real_main.py (code=exited, status=1/FAILURE)
   Main PID: 28361 (code=exited, status=1/FAILURE)
        CPU: 98ms
ubuntu@ip-172-31-42-97:~/teleaccount-bot$ sudo journalctl -u telebot -n 50
Oct 22 13:56:55 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.
Oct 22 13:57:05 ip-172-31-42-97 systemd[1]: telebot.service: Scheduled restart job, restart counter is at 132.
Oct 22 13:57:05 ip-172-31-42-97 systemd[1]: Started telebot.service - Telegram Account Selling Bot.
Oct 22 13:57:05 ip-172-31-42-97 telebot[27852]: Traceback (most recent call last):
Oct 22 13:57:05 ip-172-31-42-97 telebot[27852]:   File "/home/ubuntu/teleaccount-bot/real_main.py", line 8, in <module>
Oct 22 13:57:05 ip-172-31-42-97 telebot[27852]:     from telegram import Update
Oct 22 13:57:05 ip-172-31-42-97 telebot[27852]: ImportError: cannot import name 'Update' from 'telegram' (unknown location)
Oct 22 13:57:05 ip-172-31-42-97 systemd[1]: telebot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 13:57:05 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.
Oct 22 13:57:15 ip-172-31-42-97 systemd[1]: telebot.service: Scheduled restart job, restart counter is at 133.
Oct 22 13:57:15 ip-172-31-42-97 systemd[1]: Started telebot.service - Telegram Account Selling Bot.
Oct 22 13:57:15 ip-172-31-42-97 telebot[27858]: Traceback (most recent call last):
Oct 22 13:57:15 ip-172-31-42-97 telebot[27858]:   File "/home/ubuntu/teleaccount-bot/real_main.py", line 8, in <module>
Oct 22 13:57:15 ip-172-31-42-97 telebot[27858]:     from telegram import Update
Oct 22 13:57:15 ip-172-31-42-97 telebot[27858]: ImportError: cannot import name 'Update' from 'telegram' (unknown location)
Oct 22 13:57:15 ip-172-31-42-97 systemd[1]: telebot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 13:57:15 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.
Oct 22 13:57:22 ip-172-31-42-97 systemd[1]: /etc/systemd/system/telebot.service:25: Unit uses MemoryLimit=; please use MemoryMax>
Oct 22 13:57:25 ip-172-31-42-97 systemd[1]: telebot.service: Scheduled restart job, restart counter is at 134.
Oct 22 13:57:25 ip-172-31-42-97 systemd[1]: Started telebot.service - Telegram Account Selling Bot.
Oct 22 13:57:26 ip-172-31-42-97 telebot[28216]: Traceback (most recent call last):
Oct 22 13:57:26 ip-172-31-42-97 telebot[28216]:   File "/home/ubuntu/teleaccount-bot/real_main.py", line 8, in <module>
Oct 22 13:57:26 ip-172-31-42-97 telebot[28216]:     from telegram import Update
Oct 22 13:57:26 ip-172-31-42-97 telebot[28216]: ImportError: cannot import name 'Update' from 'telegram' (unknown location)
Oct 22 13:57:26 ip-172-31-42-97 systemd[1]: telebot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 13:57:26 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.
Oct 22 13:57:29 ip-172-31-42-97 systemd[1]: Stopped telebot.service - Telegram Account Selling Bot.
Oct 22 13:57:29 ip-172-31-42-97 systemd[1]: Started telebot.service - Telegram Account Selling Bot.
Oct 22 13:57:29 ip-172-31-42-97 telebot[28361]: Traceback (most recent call last):
Oct 22 13:57:29 ip-172-31-42-97 telebot[28361]:   File "/home/ubuntu/teleaccount-bot/real_main.py", line 8, in <module>
Oct 22 13:57:29 ip-172-31-42-97 telebot[28361]:     from telegram import Update
Oct 22 13:57:29 ip-172-31-42-97 telebot[28361]: ImportError: cannot import name 'Update' from 'telegram' (unknown location)
Oct 22 13:57:29 ip-172-31-42-97 systemd[1]: telebot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 13:57:29 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.
Oct 22 13:57:39 ip-172-31-42-97 systemd[1]: telebot.service: Scheduled restart job, restart counter is at 135.
Oct 22 13:57:39 ip-172-31-42-97 systemd[1]: Started telebot.service - Telegram Account Selling Bot.
Oct 22 13:57:39 ip-172-31-42-97 telebot[28369]: Traceback (most recent call last):
Oct 22 13:57:39 ip-172-31-42-97 telebot[28369]:   File "/home/ubuntu/teleaccount-bot/real_main.py", line 8, in <module>
Oct 22 13:57:39 ip-172-31-42-97 telebot[28369]:     from telegram import Update
Oct 22 13:57:39 ip-172-31-42-97 telebot[28369]: ImportError: cannot import name 'Update' from 'telegram' (unknown location)
Oct 22 13:57:40 ip-172-31-42-97 systemd[1]: telebot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 13:57:40 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.
Oct 22 13:57:50 ip-172-31-42-97 systemd[1]: telebot.service: Scheduled restart job, restart counter is at 136.
Oct 22 13:57:50 ip-172-31-42-97 systemd[1]: Started telebot.service - Telegram Account Selling Bot.
Oct 22 13:57:50 ip-172-31-42-97 telebot[28374]: Traceback (most recent call last):
Oct 22 13:57:50 ip-172-31-42-97 telebot[28374]:   File "/home/ubuntu/teleaccount-bot/real_main.py", line 8, in <module>
Oct 22 13:57:50 ip-172-31-42-97 telebot[28374]:     from telegram import Update
Oct 22 13:57:50 ip-172-31-42-97 telebot[28374]: ImportError: cannot import name 'Update' from 'telegram' (unknown location)
Oct 22 13:57:50 ip-172-31-42-97 systemd[1]: telebot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 13:57:50 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.
lines 1-50