ubuntu@ip-172-31-42-97:~/teleaccount-bot$ sudo systemctl restart telebot
ubuntu@ip-172-31-42-97:~/teleaccount-bot$ sudo systemctl status telebot
‚óè telebot.service - Telegram Account Selling Bot
     Loaded: loaded (/etc/systemd/system/telebot.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2025-10-22 13:45:56 UTC; 9s ago
    Process: 27488 ExecStart=/usr/bin/python3 /home/ubuntu/teleaccount-bot/real_main.py (code=exited, status=1/FAILURE)
   Main PID: 27488 (code=exited, status=1/FAILURE)
        CPU: 100ms

Oct 22 13:45:56 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.
ubuntu@ip-172-31-42-97:~/teleaccount-bot$ sudo journalctl -u telebot -n 50
Oct 22 13:45:12 ip-172-31-42-97 systemd[1]: telebot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 13:45:12 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.
Oct 22 13:45:22 ip-172-31-42-97 systemd[1]: telebot.service: Scheduled restart job, restart counter is at 64.
Oct 22 13:45:22 ip-172-31-42-97 systemd[1]: Started telebot.service - Telegram Account Selling Bot.
Oct 22 13:45:22 ip-172-31-42-97 telebot[27445]: Traceback (most recent call last):
Oct 22 13:45:22 ip-172-31-42-97 telebot[27445]:   File "/home/ubuntu/teleaccount-bot/real_main.py", line 8, in <module>
Oct 22 13:45:22 ip-172-31-42-97 telebot[27445]:     from telegram import Update
Oct 22 13:45:22 ip-172-31-42-97 telebot[27445]: ImportError: cannot import name 'Update' from 'telegram' (unknown location)
Oct 22 13:45:22 ip-172-31-42-97 systemd[1]: telebot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 13:45:22 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.
Oct 22 13:45:32 ip-172-31-42-97 systemd[1]: telebot.service: Scheduled restart job, restart counter is at 65.
Oct 22 13:45:32 ip-172-31-42-97 systemd[1]: Started telebot.service - Telegram Account Selling Bot.
Oct 22 13:45:32 ip-172-31-42-97 telebot[27467]: Traceback (most recent call last):
Oct 22 13:45:32 ip-172-31-42-97 telebot[27467]:   File "/home/ubuntu/teleaccount-bot/real_main.py", line 8, in <module>
Oct 22 13:45:32 ip-172-31-42-97 telebot[27467]:     from telegram import Update
Oct 22 13:45:32 ip-172-31-42-97 telebot[27467]: ImportError: cannot import name 'Update' from 'telegram' (unknown location)
Oct 22 13:45:33 ip-172-31-42-97 systemd[1]: telebot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 13:45:33 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.
Oct 22 13:45:43 ip-172-31-42-97 systemd[1]: telebot.service: Scheduled restart job, restart counter is at 66.
Oct 22 13:45:43 ip-172-31-42-97 systemd[1]: Started telebot.service - Telegram Account Selling Bot.
Oct 22 13:45:43 ip-172-31-42-97 telebot[27475]: Traceback (most recent call last):
Oct 22 13:45:43 ip-172-31-42-97 telebot[27475]:   File "/home/ubuntu/teleaccount-bot/real_main.py", line 8, in <module>
Oct 22 13:45:43 ip-172-31-42-97 telebot[27475]:     from telegram import Update
Oct 22 13:45:43 ip-172-31-42-97 telebot[27475]: ImportError: cannot import name 'Update' from 'telegram' (unknown location)
Oct 22 13:45:43 ip-172-31-42-97 systemd[1]: telebot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 13:45:43 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.
Oct 22 13:45:53 ip-172-31-42-97 systemd[1]: telebot.service: Scheduled restart job, restart counter is at 67.
Oct 22 13:45:53 ip-172-31-42-97 systemd[1]: Started telebot.service - Telegram Account Selling Bot.
Oct 22 13:45:53 ip-172-31-42-97 telebot[27480]: Traceback (most recent call last):
Oct 22 13:45:53 ip-172-31-42-97 telebot[27480]:   File "/home/ubuntu/teleaccount-bot/real_main.py", line 8, in <module>
Oct 22 13:45:53 ip-172-31-42-97 telebot[27480]:     from telegram import Update
Oct 22 13:45:53 ip-172-31-42-97 telebot[27480]: ImportError: cannot import name 'Update' from 'telegram' (unknown location)
Oct 22 13:45:53 ip-172-31-42-97 systemd[1]: telebot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 13:45:53 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.
Oct 22 13:45:56 ip-172-31-42-97 systemd[1]: Stopped telebot.service - Telegram Account Selling Bot.
Oct 22 13:45:56 ip-172-31-42-97 systemd[1]: Started telebot.service - Telegram Account Selling Bot.
Oct 22 13:45:56 ip-172-31-42-97 telebot[27488]: Traceback (most recent call last):
Oct 22 13:45:56 ip-172-31-42-97 telebot[27488]:   File "/home/ubuntu/teleaccount-bot/real_main.py", line 8, in <module>
Oct 22 13:45:56 ip-172-31-42-97 telebot[27488]:     from telegram import Update
Oct 22 13:45:56 ip-172-31-42-97 telebot[27488]: ImportError: cannot import name 'Update' from 'telegram' (unknown location)
Oct 22 13:45:56 ip-172-31-42-97 systemd[1]: telebot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 13:45:56 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.
Oct 22 13:46:06 ip-172-31-42-97 systemd[1]: telebot.service: Scheduled restart job, restart counter is at 68.
Oct 22 13:46:06 ip-172-31-42-97 systemd[1]: Started telebot.service - Telegram Account Selling Bot.
Oct 22 13:46:06 ip-172-31-42-97 telebot[27496]: Traceback (most recent call last):
Oct 22 13:46:06 ip-172-31-42-97 telebot[27496]:   File "/home/ubuntu/teleaccount-bot/real_main.py", line 8, in <module>
Oct 22 13:46:06 ip-172-31-42-97 telebot[27496]:     from telegram import Update
Oct 22 13:46:06 ip-172-31-42-97 telebot[27496]: ImportError: cannot import name 'Update' from 'telegram' (unknown location)
Oct 22 13:46:06 ip-172-31-42-97 systemd[1]: telebot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 13:46:06 ip-172-31-42-97 systemd[1]: telebot.service: Failed with result 'exit-code'.